AWSTemplateFormatVersion: "2010-09-09"

Description: "Resources for the Terraform-to-CloudFormation custom type handler"

Parameters:
    AllowAWSActions:
        Description: If true, AWS actions will be permitted to execute through an administrative role (required for TF::AWS::* resources)
        Type: String
        Default: 'false'
        AllowedValues:
          - "true"
          - "false"
    
    S3Bucket:
        Description: The name of the bucket that contains the Lambda source (leave blank to use latest)
        Type: String
        Default: ''
    
    S3Key:
        Description: The key of the ZIP package within the bucket (leave blank to use latest)
        Type: String
        Default: ''

Metadata: 
    AWS::CloudFormation::Interface: 
        ParameterGroups: 
          - Label: 
                default: "General Settings"
            Parameters: 
              - AllowAWSActions
          - Label: 
                default: "Advanced Configuration"
            Parameters: 
              - S3Bucket
              - S3Key
        ParameterLabels: 
            AllowAWSActions: 
                default: "Allow All AWS Actions"
            S3Bucket: 
                default: "Executor Lambda Code S3 Bucket"
            S3Key: 
                default: "Executor Lambda Code S3 Key"

Mappings:
    RegionMap:
        eu-west-1:
            bucketname: aviatrix-cfn-types-eu-west-1
        eu-west-2:
            bucketname: aviatrix-cfn-types-eu-west-2
        eu-west-3:
            bucketname: aviatrix-cfn-types-eu-west-3    
        eu-central-1:
            bucketname: aviatrix-cfn-types-eu-central-1
        us-east-1:
            bucketname: aviatrix-cfn-types-us-east-1
        us-east-2:
            bucketname: aviatrix-cfn-types-us-east-2
        us-west-1:
            bucketname: aviatrix-cfn-types-us-west-1
        us-west-2:
            bucketname: aviatrix-cfn-types-us-west-2
        ca-central-1:
            bucketname: aviatrix-cfn-types-ca-central-1
        eu-north-1:
            bucketname: aviatrix-cfn-types-eu-north-1
        ap-south-1:
            bucketname: aviatrix-cfn-types-ap-south-1
        ap-southeast-1:
            bucketname: aviatrix-cfn-types-ap-southeast-1
        ap-southeast-2:
            bucketname: aviatrix-cfn-types-ap-southeast-2
        ap-northeast-1:
            bucketname: aviatrix-cfn-types-ap-northeast-1
        ap-northeast-2:
            bucketname: aviatrix-cfn-types-ap-northeast-2
        sa-east-1:
            bucketname: aviatrix-cfn-types-sa-east-1

Conditions:
    S3Defined: !Not [ !Equals [ '', !Ref S3Bucket ] ]
    AllowAWS: !Equals [ 'true', !Ref AllowAWSActions ]

Resources:
    StateS3Bucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Sub "cfntf-${AWS::Region}-${AWS::AccountId}"
            BucketEncryption:
                ServerSideEncryptionConfiguration:
                  - ServerSideEncryptionByDefault:
                        SSEAlgorithm: AES256
            PublicAccessBlockConfiguration:
                BlockPublicAcls: true
                BlockPublicPolicy: true
                IgnorePublicAcls: true
                RestrictPublicBuckets: true

    ExecutorLambdaServiceRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Principal:
                        Service: lambda.amazonaws.com
                    Action: sts:AssumeRole
            Path: /
            Policies:
              - PolicyName: CoreFunctionality
                PolicyDocument:
                    Version: '2012-10-17'
                    Statement:
                      - Effect: Allow
                        Action:
                          - logs:CreateLogGroup
                          - logs:CreateLogStream
                          - logs:PutLogEvents
                        Resource: "*"
                      - Effect: Allow
                        Action: secretsmanager:GetSecretValue
                        Resource: !Sub "arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:terraform/*"
                      - Effect: Allow
                        Action:
                          - s3:GetObject
                          - s3:PutObject
                          - s3:DeleteObject
                        Resource: !Sub "${StateS3Bucket.Arn}/*"
              - !If
                  - "AllowAWS"
                  - PolicyName: AWSActions
                    PolicyDocument:
                        Version: '2012-10-17'
                        Statement:
                          - Effect: Allow
                            Action: '*'
                            Resource: '*'
                  - !Ref "AWS::NoValue"

    ExecutorLambdaLogGroup:
        Type: AWS::Logs::LogGroup
        Properties:
            LogGroupName: "/aws/lambda/cfntf-executor"
            RetentionInDays: 14

    ExecutorLambdaFunction:
        Type: AWS::Lambda::Function
        Properties:
            FunctionName: cfntf-executor
            Handler: index.handler
            Role: !GetAtt ExecutorLambdaServiceRole.Arn
            Environment:
                Variables:
                    BUCKET: !Ref StateS3Bucket
            Code:
                S3Bucket: !If
                  - S3Defined
                  - !Ref S3Bucket
                  - Fn::FindInMap:
                      - RegionMap
                      - !Ref AWS::Region
                      - bucketname
                S3Key: !If
                  - S3Defined
                  - !Ref S3Key
                  - app.zip
            Runtime: python3.8
            MemorySize: 1024
            Timeout: 900
    
    ExecutorLambdaInvokeConfig:
        Type: AWS::Lambda::EventInvokeConfig
        Properties:
            FunctionName: !Ref ExecutorLambdaFunction
            MaximumRetryAttempts: 2
            Qualifier: "$LATEST"

    ExecutionRole:
        Type: AWS::IAM::Role
        Properties:
            MaxSessionDuration: 8400
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Principal:
                        Service: resources.cloudformation.amazonaws.com
                    Action: sts:AssumeRole
            Path: "/"
            Policies:
              - PolicyName: ResourceTypePolicy
                PolicyDocument:
                    Version: '2012-10-17'
                    Statement:
                      - Effect: Allow
                        Action:
                          - "lambda:InvokeFunction"
                          - "s3:DeleteObject"
                          - "s3:GetObject"
                          - "s3:ListBucket"
                        Resource: "*"

Outputs:

    ExecutionRoleARN:
        Description: The execution role ARN to use for registered types
        Value: !GetAtt ExecutionRole.Arn
